# ------------------------------
# Site & Theme Settings
# ------------------------------
theme: minima
title: "Kristopher Taylor<br><span style='font-size:0.7em;font-weight:400;'>Security Engineer · Cloud · Linux · AI</span>"
description: "A living portfolio of labs, builds, and experiments"
url: "https://kristophertaylorsec.github.io"
baseurl: ""

# ------------------------------
# Markdown & Code Rendering
# ------------------------------
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter_opts:
    block:
      line_numbers: false

# ------------------------------
# Include Folders (so everything builds)
# ------------------------------
include:
  - projects
  - assets
  -
