theme: jekyll-theme-slate
title: "Kristopher Taylor<br><span style='font-size:0.7em;font-weight:400;'>Security Engineer · Cloud · Linux · AI</span>"
description: "A living portfolio of labs, builds, and experiments"
url: "https://kristophertaylorsec.github.io"
baseurl: ""

# --- Jekyll settings for proper code block rendering ---
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter_opts:
    block:
      line_numbers: false

# --- Include all project folders for deep file rendering ---
include:
  - projects
