site_name: Continuous Mastery Journal
site_description: A professional, documentation-first portfolio showcasing applied work across systems, cloud, cybersecurity, software, and infrastructure.
site_author: Kristopher Taylor
repo_url: https://github.com/KristopherTaylorSec/TechPProvingGround
repo_name: GitHub
edit_uri: edit/main/docs/

theme:
  name: material
  # Calm, readable, accessible palette with dark-mode toggle
  palette:
    - scheme: default
      primary: blue grey
      accent: light blue
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      primary: blue grey
      accent: light blue
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  font:
    text: Inter
    code: Roboto Mono
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.instant
    - toc.integrate
    - content.code.annotate
    - content.action.edit
    - search.suggest
    - search.highlight

extra:
  social:
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/<your-linkedin-handle>/
    - icon: fontawesome/brands/github
      link: https://github.com/<your-new-username>

extra_css:
  - assets/extra.css

nav:
  - Home: index.md
  - Linux: linux.md
  - Cloud: cloud.md
  - Cybersecurity: cybersecurity.md
  - Software: software.md
  - Infrastructure: infrastructure.md

markdown_extensions:
  - admonition
  - attr_list
  - footnotes
  - tables
  - toc:
      permalink: true
  - pymdownx.details
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: true
